### ISSUE TITLE
Follow on from twitter, JS Architecture help

### ISSUE THREAD

**Issue by matt3224** [webpro/DOMtastic#46]
Hey Lars,

Sorry to bother you with more questions, I really appreciate your help and advise on this though!

I couldn't explain what I want to do in 140 characters so I am using the repo. I have a framework/library currently written all in es5 using standard iife's. I would like to modernise the framework/library by using es6 modules.

I want to use DOMtastic as the base for my framework components (things like modals, tabs etc.) and I would like to rebuild them so they can be chained `$('.myelem').modal(); I would like to use factory functions to achieve this rather than classes and for each one to be imported as an es6 module.

These would be globally callable without importing `$` in non es6 scripts. I am using rollup and babel to bundle and transpile my code.

I'm finding it a little difficult to modernise my code as although there is plenty online about es6 modules, it feels like what i'm trying to do is too niche to be documented yet. Either that or i'm misunderstanding how to implement this stuff.

Many thanks for any insight on what i'm trying to do here.

**Comment by webpro** [comment]
> I want to use DOMtastic as the base for my framework components (things like modals, tabs etc.) and I would like to rebuild them so they can be chained `$('.myelem').modal();

You can extend `$.fn` like jQuery plugins (also see https://github.com/webpro/DOMtastic#but-it-doesnt-even-have-awesomest-method) for stuff like `$('.myelem').modal()`. Or isn't this what you mean?

> I would like to use factory functions to achieve this rather than classes and for each one to be imported as an es6 module.

Do you mean you want to import e.g. the `modal` component separately? You could `import modal from './components/modal'` in some central place where all components are attached to `$.fn`.

> These would be globally callable without importing $ in non es6 scripts.

I'm not sure how everything ends up in your situation, but if necessary you can always attach `$` to the global scope from your framework code (since it imports `$` anyway).

**Comment by matt3224** [comment]
Yes `$.fn` is what I would use. I saw your base class and wondered if I could use factory functions in a similar way. I have recently managed to solve my bundling issues and have that all working nicely now.

Thanks for your help, i'll close the issue and let you take a look at my project once I have made something half decent to see what you think.

Cheers!
